apiVersion: v1
kind: Namespace
metadata:
  name: polaris
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8ssandra-efficiency-metric-controller
  namespace: polaris
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # ClusterRoles are not namespaced
  name: k8ssandra-efficiency-metric-controller
rules:
  # Allow reading all Composed Metric Mapping types
  # - apiGroups:
  #   - metrics.polaris-slo-cloud.github.io
  #   resources:
  #   - "*"
  #   verbs:
  #   - get
  #   - watch
  #   - list

  # Allow reading supported Composed Metric Mapping types
  - apiGroups:
      - metrics.polaris-slo-cloud.github.io
    resources:
      - k8ssandraefficiencymetricmappings
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - metrics.polaris-slo-cloud.github.io
    resources:
      - k8ssandraefficiencymetricmappings/status
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
# Optionally, we could create a RoleBinding and to scope the permissions to a specific namespace
metadata:
  name: control-k8ssandraefficiencymetricmappings
subjects:
  - kind: ServiceAccount
    name: k8ssandra-efficiency-metric-controller
    namespace: polaris
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8ssandra-efficiency-metric-controller
